repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
    -   id: name-tests-test
        args: ["--pytest-test-first"]
        exclude: test/conftest.py
    -   id: pretty-format-json
        args: ["--autofix"]
    -   id: requirements-txt-fixer
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
    -   id: ruff-check
        args: [--fix]
-   repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
    -   id: black
