
# === Knapsack algorithm configuration file ===


# --- DATA AND FILEPATHS ---
data:
  filename: "f2_l-d_kp_20_878"   # Filename without path from "dane AG 2" file
  max_weight: 878                  # Max weight threshold for GA

# --- POPULATION PARAMETERS ---
population:
  size: 10                        # population_size (N)
  generations: 100                  # generations (number of algorithm's iterations)
  stream_batch_size: 50            # stream_batch_size (size of memory i/o batch)

# --- SELECTION MODIFIER ---
selection:
  type: "tournament"              # Type of parent selection [roulette, tournament, rank]
  selection_pressure: 1                           # Only applicable for rank selection in range [1 - 2] (float)

# --- GENETIC OPERATORS ---
genetic_operators:
  crossover_type: "two"             # Type of crossover method [one, two] (points of slicing)
  crossover_probability: 0.6        # Probability of crossover occurrence (Pc)
  mutation_probability: 0.05         # Probability of mutation occurrence (Pm)
  penalty_multiplier: 0             # Penalty factor applied after exceeding threshold weight (0 - nullifies fitness if weight exceeded)

# --- EXPERIMENT VARIABLES ---
experiment:
  seed: 2137                        # Predefined RNG seed (if null, rng will be defined randomly)
  identifier: 0                     # Experiment identifier (will be defined in next versions)
  log_level: INFO                   # Level of logged events [DEBUG, INFO, WARNING, ERROR, CRITICAL]